# Generated by Django 5.0.2 on 2024-02-18 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maxsulot_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='MistakeFiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xato_id', models.CharField(max_length=255, unique=True)),
                ('problem_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mistakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='MistakeFiles/')),
                ('izoh', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('xato_soni', models.PositiveIntegerField(null=True)),
                ('butun_soni', models.PositiveIntegerField(null=True)),
                ('ish_vaqti', models.PositiveIntegerField(null=True)),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsluot', to='Mistakes.maxsulot')),
            ],
        ),
    ]
