# Generated by Django 5.0.2 on 2024-02-18 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mistakes', '0001_initial'),
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mistakes',
            name='xodim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xodim', to='User.xodim'),
        ),
        migrations.AddField(
            model_name='mistakes',
            name='rasm',
            field=models.ManyToManyField(related_name='MistakesPhoto', to='Mistakes.photo'),
        ),
        migrations.AddField(
            model_name='mistakes',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='Mistakes.problem'),
        ),
    ]
