# Generated by Django 5.0.2 on 2024-02-18 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mistakes', '0002_initial'),
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mistakes',
            new_name='Hisobot',
        ),
        migrations.RenameField(
            model_name='hisobot',
            old_name='file',
            new_name='files',
        ),
        migrations.AlterField(
            model_name='maxsulot',
            name='maxsulot_id',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='xato_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
