# Generated by Django 5.0.2 on 2024-02-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mistakes', '0003_rename_mistakes_hisobot_rename_file_hisobot_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='Mistakes.problem'),
        ),
        migrations.AlterField(
            model_name='hisobot',
            name='xato_soni',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
