# Generated by Django 5.0.2 on 2024-02-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mistakes', '0004_alter_hisobot_problem_alter_hisobot_xato_soni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hisobot',
            old_name='files',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='hisobot',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='hisobot',
            old_name='maxsulot',
            new_name='mahsulot',
        ),
        migrations.RenameField(
            model_name='hisobot',
            old_name='rasm',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='hisobot',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='hisobot',
            old_name='problem',
            new_name='xato',
        ),
        migrations.RenameField(
            model_name='maxsulot',
            old_name='maxsulot_id',
            new_name='mahsulot_id',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='hisobot',
            name='butun_soni',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hisobot',
            name='xato_soni',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
