# Generated by Django 5.0.2 on 2024-03-03 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mistakes', '0005_rename_files_hisobot_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulot', to='Mistakes.maxsulot'),
        ),
    ]
