# Generated by Django 5.0.2 on 2024-03-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mistakes', '0006_alter_hisobot_mahsulot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulot',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
