# Generated by Django 5.0.2 on 2024-03-18 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mistakes', '0008_alter_hisobot_mahsulot_alter_hisobot_user_and_more'),
        ('User', '0006_alter_bolim_user_alter_xodim_bulimi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot',
            name='mahsulot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maxsulot', to='Mistakes.maxsulot'),
        ),
        migrations.AlterField(
            model_name='hisobot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hisobot',
            name='xato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem', to='Mistakes.problem'),
        ),
        migrations.AlterField(
            model_name='hisobot',
            name='xodim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xodim', to='User.xodim'),
        ),
    ]
