# Generated by Django 5.0.2 on 2024-03-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mistakes', '0009_alter_hisobot_mahsulot_alter_hisobot_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hisobot',
            name='ish_vaqti',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hisobot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
