# Generated by Django 5.0.2 on 2024-03-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mistakes', '0010_alter_hisobot_created_at_alter_hisobot_ish_vaqti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot',
            name='ish_vaqti',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
