# Generated by Django 5.0.2 on 2024-02-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol'), ('Null', 'Null')], max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_photos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Diretor', 'Diretor'), ('Admin', 'Admin'), ('Tekshiruvchi', 'Tekshiruvchi'), ('Bulum', 'Bulum')], max_length=13),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='gender',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol'), ('Null', 'Null')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='xodim_photos'),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
