# Generated by Django 5.0.2 on 2024-03-18 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_bolim_user_alter_xodim_bulimi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolim',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='bulimi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bolim', to='User.bolim'),
        ),
    ]
