# Generated by Django 5.0.2 on 2024-03-20 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_bolim_user_alter_xodim_bulimi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xodim',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='xodim',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='xodim',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='xodim',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='xodim',
            name='photo',
        ),
        migrations.AddField(
            model_name='xodim',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xodim_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
