# Generated by Django 5.0.2 on 2024-03-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Direktor', 'Direktor'), ('Admin', 'Admin'), ('Tekshiruvchi', 'Tekshiruvchi'), ('Bulim', 'Bulim'), ('Xodim', 'Xodim')], default='Xodim', max_length=13),
        ),
    ]
