# Generated by Django 5.0.2 on 2024-03-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_user_status_remove_xodim_id_raqam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_bulim',
        ),
        migrations.AddField(
            model_name='user',
            name='is_tekshiruvchi',
            field=models.BooleanField(default=False),
        ),
    ]
