# Generated by Django 5.0.2 on 2024-03-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_rename_is_manager_user_is_bulim_user_is_tekshiruvchi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='user_photos'),
        ),
    ]
