# Generated by Django 5.0.2 on 2024-03-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodim',
            name='bulimi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bolim', to='User.bolim'),
        ),
    ]
