# Generated by Django 5.0.2 on 2024-03-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_xodim_bulimi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_director',
            new_name='is_direktor',
        ),
    ]
